language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

env: MINIMUM_VERSIONS=false

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: MINIMUM_VERSIONS=true
  allow_failures:
    - php: nightly

install:
  - if [[ $MINIMUM_VERSIONS = false ]]; then composer install; fi
  - if [[ $MINIMUM_VERSIONS = true ]]; then composer update --no-interaction --prefer-lowest; fi

script:
  - vendor/bin/phpunit
